/**
 * UI copy, pt-BR, centralized (§1.3 / §6.3 of INITIAL_PLAN).
 * No i18n framework by design — extraction later is mechanical.
 */
export const strings = {
  app: {
    name: "UeceTexLive",
    tagline: "Sua monografia UECE, do texto ao PDF, no navegador.",
    loading: "Preparando seu editor…",
  },
  topbar: {
    compile: "Gerar PDF",
    compiling: "Gerando PDF…",
    warming: "Preparando motor…",
    export: "Exportar",
    exportPdf: "Baixar PDF",
    exportZip: "Exportar projeto (.zip)",
    menu: "Menu",
    importZip: "Importar ZIP",
    importBbl: "Importar .bbl",
    resetTemplate: "Restaurar modelo",
    about: "Sobre",
    saving: "Salvando…",
    saved: "Salvo",
    toggleRail: "Painel lateral (Ctrl/Cmd+B): mostrar ou ocultar a árvore de arquivos.",
    compileHint: "Gerar PDF (Ctrl/Cmd+Enter): atualiza o PDF com as últimas edições.",
    menuHint:
      "Menu: importar ZIP, exportar PDF ou projeto, importar .bbl, restaurar modelo.",
    viewToggleHint: "Alternar entre fonte LaTeX e editor visual (Ctrl/Cmd+E).",
    idleWarmup: "Preparando motor completo:",
    idleWarmupHint:
      "Baixando o motor do modo Completo em segundo plano (~150 MB, uma única vez) — você já pode escrever e usar o Rascunho normalmente.",
  },
  engine: {
    toggleLabel: "Modo de geração do PDF",
    draft: "Rascunho",
    draftHint: "Rascunho rápido — não resolve citações, glossário nem índice.",
    full: "Completa",
    fullHint: "PDF completo — resolve citações, glossário e índice.",
    fullWarning:
      "Gerar o PDF completo baixa ~150 MB na primeira vez (uma única vez — fica salvo no navegador) e resolve bibliografia, glossário e índice. O rascunho é instantâneo, mas mostra [?] nas citações.",
    draftBanner:
      "Modo rascunho: citações, glossário e índice não são resolvidos. Use o modo Completo para o PDF final.",
  },
  rail: {
    preTextual: "Pré-textuais",
    chapters: "Capítulos",
    postTextual: "Pós-textuais",
    library: "Biblioteca",
    figures: "Anexos",
    missingInclude: "Arquivo não encontrado — clique para criar",
    newChapter: "Novo capítulo",
    newChapterPrompt: "Título do novo capítulo:",
    newChapterPlaceholder: "Ex.: “Estudo de Caso”",
    newChapterCreate: "Criar capítulo",
    newChapterCancel: "Cancelar",
    hiddenFileSingular: "arquivo avançado oculto",
    hiddenFilesPlural: "arquivos avançados ocultos",
    hiddenFilesHint: "Marque “Avançado” na barra superior para vê-los",
    showHiddenFiles: "mostrar",
    uploadFile: "Enviar arquivo (imagem, PDF ou código)",
    uploadFileError:
      "Não foi possível enviar (use PNG, JPG, PDF ou código-fonte de até 10 MB):",
    unsavedChanges: "Alterações não salvas",
  },
  editor: {
    rawLatexTooltip:
      "LaTeX bruto — o UeceTexLive preserva este trecho exatamente como está",
    sourceView: "Fonte LaTeX",
    wysiwygView: "Editor visual",
    placeholder: "Escreva, ou digite / para inserir…",
    wordSingular: "palavra",
    wordsPlural: "palavras",
    wordsInWork: "no trabalho",
    uploadImage: "Enviar imagem ou PDF do computador…",
    uploadImageError: "Não foi possível enviar — use PNG, JPG ou PDF de até 10 MB.",
    find: "Localizar",
    findHint: "Localizar e substituir (Ctrl+F)",
    findPlaceholder: "Localizar",
    findReplacePlaceholder: "Substituir",
    findNext: "próximo",
    findPrev: "anterior",
    findReplace: "substituir",
    findReplaceAll: "substituir tudo",
    findCase: "diferenciar maiúsculas",
    findWord: "palavra inteira",
    findRegex: "regex",
    findClose: "fechar",
    findNoMatches: "nenhuma ocorrência",
    tableLabel: "Tabela",
    editAsLatex: "editar como LaTeX",
  },
  toolbar: {
    bold: "Negrito",
    italic: "Itálico",
    underline: "Sublinhado",
    code: "Monoespaçado",
    chapter: "Título de capítulo",
    section: "Seção",
    subsection: "Subseção",
    bulletList: "Lista com marcadores",
    orderedList: "Lista numerada",
    blockquote: "Citação longa (ABNT 4cm)",
    citation: "Citação bibliográfica",
    crossref: "Referência cruzada",
    figure: "Inserir figura",
    table: "Inserir tabela",
    equation: "Inserir equação",
  },
  metadata: {
    title: "Dados do Trabalho",
    railEntry: "Dados do Trabalho",
    stepsLabel: "Etapas",
    pendingHint: "Preencha o título e os dados do seu trabalho",
    missingMacro: "Não encontrado no documento.tex — edite pelo modo Avançado",
    themeContext: "Seu tema:",
    prev: "Anterior",
    next: "Avançar",
    done: "Concluir",
    close: "Fechar",
    welcomeTitle: "Bem-vindo ao UeceTexLive!",
    welcomeBody:
      "Comece preenchendo os dados do seu trabalho — título, tipo (TCC, dissertação…), autor e orientador. A capa e a folha de rosto são montadas automaticamente no padrão da UECE.",
    welcomeFill: "Preencher dados",
    welcomeLater: "Depois",
  },
  preview: {
    empty: "Gere o PDF para ver aqui.",
    stale: "Gerando PDF…",
    logTab: "Detalhes",
    pdfTab: "PDF",
    invert: "Modo escuro do PDF (inverter cores)",
  },
  diagnostics: {
    error: "erro",
    warning: "aviso",
    rawExcerpt: "ver texto original",
  },
  rescue: {
    corruptState:
      "Encontramos um estado salvo incompatível. Seu estado anterior foi exportado como zip e o modelo foi restaurado.",
  },
  shell: {
    templateUpdateMessage:
      "O modelo uecetex2 foi atualizado. Seu conteúdo não foi afetado.",
    templateUpdateDismiss: "Dispensar",
    bblImportedNote:
      "O próximo PDF completo usará esta bibliografia pré-compilada e pulará o BibTeX (útil para projetos biber).",
    telemetryNoticeMessage:
      "Entre 06 e 09/07 esta versão coleta eventos anônimos de uso (gerar PDF, exportar) para um TCC — nenhum conteúdo do seu documento é enviado.",
    telemetryNoticeLink: "Saiba mais / dê seu feedback",
    telemetryNoticeDismiss: "Fechar aviso",
  },
  sobre: {
    title: "Sobre o UeceTexLive",
    privacy: "Tudo acontece no seu navegador: seu texto nunca sai do seu computador.",
  },
} as const;
