/**
 * UI copy, pt-BR, centralized (copy rules in README, "Regras de copy").
 * No i18n framework by design — extraction later is mechanical.
 */
export const strings = {
  app: {
    name: "UeceTexLive",
    tagline: "Sua monografia UECE, do texto ao PDF, no navegador.",
    loading: "Preparando seu editor…",
  },
  topbar: {
    compile: "Gerar PDF",
    compiling: "Gerando PDF…",
    warming: "Preparando motor…",
    export: "Exportar",
    exportPdf: "Baixar PDF",
    exportZip: "Exportar projeto (.zip)",
    menu: "Menu",
    importZip: "Importar ZIP",
    importBbl: "Importar .bbl",
    resetTemplate: "Restaurar modelo",
    about: "Sobre",
    saving: "Salvando…",
    saved: "Salvo",
    toggleRail: "Painel lateral (Ctrl/Cmd+B): mostrar ou ocultar a árvore de arquivos.",
    openGuide: "Guia do trabalho…",
    compileHint: "Gerar PDF (Ctrl/Cmd+Enter): atualiza o PDF com as últimas edições.",
    menuHint:
      "Menu: importar ZIP, importar PDF, exportar PDF ou projeto, importar .bbl, restaurar modelo.",
    viewToggleHint: "Alternar entre fonte LaTeX e editor visual (Ctrl/Cmd+E).",
    bibViewToggleHint:
      "Alternar entre a fonte BibTeX e a lista de referências (Ctrl/Cmd+E).",
    idleWarmup: "Preparando motor completo:",
    idleWarmupHint:
      "Baixando o motor do modo Completo em segundo plano (~150 MB, uma única vez) — você já pode escrever e usar o Rascunho normalmente.",
  },
  engine: {
    toggleLabel: "Modo de geração do PDF",
    draft: "Rascunho",
    draftHint: "Rascunho rápido — não resolve citações, glossário nem índice.",
    full: "Completa",
    fullHint: "PDF completo — resolve citações, glossário e índice.",
    fullWarning:
      "Gerar o PDF completo baixa ~150 MB na primeira vez (uma única vez — fica salvo no navegador) e resolve bibliografia, glossário e índice. O rascunho é instantâneo, mas mostra [?] nas citações.",
    draftBanner:
      "Modo rascunho: citações, glossário e índice não são resolvidos. Use o modo Completo para o PDF final.",
  },
  rail: {
    filesTab: "Arquivos",
    complianceTab: "Conformidade",
    preTextual: "Pré-textuais",
    chapters: "Capítulos",
    postTextual: "Pós-textuais",
    library: "Biblioteca",
    figures: "Anexos",
    missingInclude: "Arquivo não encontrado — clique para criar",
    newChapter: "Novo capítulo",
    newChapterPrompt: "Título do novo capítulo:",
    newChapterPlaceholder: "Ex.: “Estudo de Caso”",
    newChapterCreate: "Criar",
    newChapterTarget: "Onde entra no trabalho",
    targetChapter: "Capítulo",
    targetApendice: "Apêndice — material que você mesmo produziu",
    targetAnexo: "Anexo — documento de terceiros",
    newChapterCancel: "Cancelar",
    hiddenFileSingular: "arquivo avançado oculto",
    hiddenFilesPlural: "arquivos avançados ocultos",
    hiddenFilesHint: "Marque “Avançado” na barra superior para vê-los",
    showHiddenFiles: "mostrar",
    uploadFile: "Enviar arquivo (imagem, PDF ou código)",
    uploadFileError:
      "Não foi possível enviar (use PNG, JPG, PDF ou código-fonte de até 10 MB):",
    unsavedChanges: "Alterações não salvas",
    bibFileHint:
      "Este arquivo guarda suas referências bibliográficas. Clique para abri-lo — ele tem uma edição visual, com busca e formulário por referência.",
    toggleInclude: "Aparece no PDF — desmarque para tirar",
    toggleExcluded: "Fora do PDF — marque para incluir",
  },
  importPdf: {
    menuEntry: "Importar PDF (experimental)…",
    welcomeButton: "Já tenho meu TCC em PDF",
    title: "Importar um PDF",
    experimental: "Experimental",
    intro:
      "Lemos o PDF aqui no seu navegador — o arquivo não sai do seu computador — e montamos um projeto a partir dele. Funciona bem com PDFs feitos no modelo da UECE.",
    stageLendo: "Lendo o PDF…",
    stageReconhecendo: "Reconhecendo capítulos e figuras…",
    stageMontando: "Montando o projeto…",
    reportTitle: "O que reconhecemos",
    pendingTitle: "O que vai precisar da sua mão",
    create: "Criar projeto",
    cancel: "Cancelar",
    replaceWarning:
      "Criar o projeto substitui o que está aberto agora. Exporte uma cópia antes, se quiser guardar.",
    errorType: "Escolha um arquivo PDF — este não parece ser um.",
    errorSize: "O arquivo passa de 40 MB. Um TCC costuma ter bem menos que isso.",
    errorTitle: "Não deu para importar",
    retry: "Escolher outro arquivo",
    lowConfidence:
      "Este PDF não parece ter sido gerado pelo modelo da UECE. A importação funciona bem apenas para PDFs desse modelo — em outros, o texto costuma sair embaralhado.",
    tryAnyway: "Tentar mesmo assim",
    errorResources:
      "Não foi possível ler este PDF neste navegador — provavelmente faltou memória. Feche outras abas e tente de novo; se persistir, um PDF menor costuma passar.",
    pendencyLabels: {
      equacao: {
        one: "equação precisa ser refeita",
        many: "equações precisam ser refeitas",
      },
      "equacao-inline": {
        one: "equação inline precisa ser revisada",
        many: "equações inline precisam ser revisadas",
      },
      algoritmo: {
        one: "algoritmo precisa ser reconstruído",
        many: "algoritmos precisam ser reconstruídos",
      },
      "nota-rodape": {
        one: "nota de rodapé precisa voltar ao lugar certo",
        many: "notas de rodapé precisam voltar ao lugar certo",
      },
      "citacao-nao-ligada": {
        one: "citação não foi ligada às referências",
        many: "citações não foram ligadas às referências",
      },
      "nao-classificado": {
        one: "trecho não entrou em nenhum capítulo",
        many: "trechos não entraram em nenhum capítulo",
      },
      "figura-sem-imagem": {
        one: "figura ficou sem a imagem",
        many: "figuras ficaram sem a imagem",
      },
    },
  },
  ficha: {
    missing: "Seu projeto ainda não tem uma ficha catalográfica.",
    fromTemplate: "Ainda é a ficha de exemplo do modelo.",
    uploaded: "Ficha enviada por você.",
    upload: "Enviar a ficha da biblioteca (PDF)",
    errorType: "Envie o PDF que a biblioteca gerou — o arquivo não parece ser um PDF.",
    errorSize: "O arquivo passa de 5 MB. A ficha catalográfica tem uma página só.",
  },
  editor: {
    rawLatexTooltip:
      "LaTeX bruto — o UeceTexLive preserva este trecho exatamente como está",
    sourceView: "Fonte LaTeX",
    wysiwygView: "Editor visual",
    bibSourceView: "Fonte BibTeX",
    bibVisualView: "Referências",
    placeholder: "Escreva, ou digite / para inserir…",
    wordSingular: "palavra",
    wordsPlural: "palavras",
    wordsInWork: "no trabalho",
    uploadImage: "Enviar imagem ou PDF do computador…",
    uploadImageError: "Não foi possível enviar — use PNG, JPG ou PDF de até 10 MB.",
    find: "Localizar",
    findHint: "Localizar e substituir (Ctrl+F)",
    findPlaceholder: "Localizar",
    findReplacePlaceholder: "Substituir",
    findNext: "próximo",
    findPrev: "anterior",
    findReplace: "substituir",
    findReplaceAll: "substituir tudo",
    findCase: "diferenciar maiúsculas",
    findWord: "palavra inteira",
    findRegex: "regex",
    findClose: "fechar",
    findNoMatches: "nenhuma ocorrência",
    tableLabel: "Tabela",
    editAsLatex: "editar como LaTeX",
  },
  toolbar: {
    bold: "Negrito",
    italic: "Itálico",
    underline: "Sublinhado",
    code: "Monoespaçado",
    chapter: "Título de capítulo",
    section: "Seção",
    subsection: "Subseção",
    bulletList: "Lista com marcadores",
    orderedList: "Lista numerada",
    blockquote: "Citação longa (ABNT 4cm)",
    citation: "Citação bibliográfica",
    crossref: "Referência cruzada",
    figure: "Inserir figura",
    table: "Inserir tabela",
    equation: "Inserir equação",
  },
  metadata: {
    title: "Dados do Trabalho",
    railEntry: "Dados do Trabalho",
    stepsLabel: "Etapas",
    pendingHint: "Preencha o título e os dados do seu trabalho",
    missingMacro:
      "Este campo não existe no arquivo do seu projeto. Ative o modo Avançado, abra o arquivo correspondente e acrescente a linha que falta.",
    savedBadge: "salvo",
    guideTitle: "Guia do trabalho",
    reviewReady: "Tudo que é obrigatório já está preenchido.",
    themeContext: "Seu tema:",
    prev: "Anterior",
    next: "Avançar",
    done: "Concluir",
    close: "Fechar",
    welcomeTitle: "Bem-vindo ao UeceTexLive!",
    welcomeBody:
      "Comece preenchendo os dados do seu trabalho — título, tipo (TCC, dissertação…), autor e orientador. A capa e a folha de rosto são montadas automaticamente no padrão da UECE.",
    welcomeFill: "Preencher dados",
    welcomeLater: "Depois",
  },
  preview: {
    empty: "Gere o PDF para ver aqui.",
    stale: "Gerando PDF…",
    logTab: "Detalhes",
    pdfTab: "PDF",
    invert: "Modo escuro do PDF (inverter cores)",
  },
  diagnostics: {
    error: "erro",
    warning: "aviso",
    rawExcerpt: "ver texto original",
  },
  rescue: {
    corruptState:
      "Encontramos um estado salvo incompatível. Seu estado anterior foi exportado como zip e o modelo foi restaurado.",
  },
  shell: {
    templateUpdateMessage:
      "O modelo uecetex2 foi atualizado. Seu conteúdo não foi afetado.",
    templateUpdateDismiss: "Dispensar",
    engineUpdateMessage:
      "Uma nova versão do UeceTexLive já foi baixada e está pronta. Seu trabalho está salvo.",
    engineUpdateReload: "Atualizar agora",
    engineUpdateDismiss: "Depois",
    backupReminderMessage: "Já faz um tempo — que tal baixar uma cópia de segurança?",
    backupReminderExport: "Baixar backup (.zip)",
    backupReminderDismiss: "Depois",
    bblImportedNote:
      "O próximo PDF completo usará esta bibliografia pré-compilada e pulará o BibTeX (útil para projetos biber).",
  },
  references: {
    empty: "Nenhuma referência ainda.",
    noBibFile: "Não encontramos um arquivo de referências (.bib) no seu projeto.",
    sortFile: "ordem do arquivo",
    sortAuthor: "autor",
    sortYear: "ano",
    unreadableCard: "Não consegui ler esta referência",
    unreadableHint:
      "O texto abaixo foi mantido exatamente como estava — nada foi apagado.",
    untitled: "(sem título)",
    unknownAuthor: "(sem autor)",
    unknownYear: "—",
    addNew: "Nova referência",
    pickTypeTitle: "Que tipo de referência é essa?",
    back: "Voltar",
    cancel: "Cancelar",
    save: "Adicionar",
    advancedSection: "Avançado",
    citationKeyLabel: "Código da citação",
    citationKeyHint:
      "Gerado automaticamente — só é usado internamente, você não precisa digitá-lo ao citar.",
    authorsLabel: "Autores",
    addAuthor: "+ adicionar autor",
    removeAuthor: "Remover autor",
    firstNamePlaceholder: "Nome",
    lastNamePlaceholder: "Sobrenome",
    requiredHint: "obrigatório",
    otherFieldsSection: "Outros campos",
    saveError: "Não foi possível salvar — confira os campos e tente de novo.",
    editTitle: "Editar referência",
    saveEdit: "Salvar",
    citationKeyReadOnlyHint:
      "O código da citação não muda aqui — isso afetaria os textos que já citam esta referência.",
    editButton: "Editar",
    removeButton: "Remover",
    editUnsupportedType:
      "Este tipo de referência só pode ser editado pelo código (toggle “ver código”).",
    removeConfirmTitle: "Remover esta referência?",
    removeConfirmUsedOne: "Esta referência é usada 1 vez no seu texto.",
    removeConfirmUsedMany: "Esta referência é usada {n} vezes no seu texto.",
    removeConfirmCancel: "Cancelar",
    removeConfirmButton: "Remover mesmo assim",
    removeError: "Não foi possível remover — tente de novo.",
    incompleteMissingPrefix: "Faltam:",
    incompleteAction: "completar",
    incompleteAggregateOne: "1 referência incompleta",
    incompleteAggregateMany: "{n} referências incompletas",
    incompleteGroupLabel: "Faltam dados nestas",
    completeGroupLabel: "Completas",
    goToFirstIncomplete: "ir para a primeira",
    focusedAnnouncement: "Referência {key} pronta para edição.",
    focusNotFound: "Referência {key} não está na lista.",
    summaryOne: "1 referência",
    summaryMany: "{n} referências",
    summaryIncomplete: "{n} incompletas",
    summaryIncompleteOne: "1 incompleta",
    typeDescriptions: {
      article: "Publicado em periódico científico",
      inproceedings: "Publicado nos anais de um evento/congresso",
      book: "Obra completa publicada",
      incollection: "Capítulo dentro de um livro com outros autores",
      phdthesis: "Trabalho de doutorado",
      mastersthesis: "Trabalho de mestrado",
      techreport: "Documento técnico de uma instituição",
      misc: "Site, vídeo ou outro material avulso",
      unpublished: "Manuscrito ou trabalho ainda não publicado",
    },
    searchPlaceholder: "Busque por título, autor ou DOI — ex.: “Pedagogia do Oprimido”",
    searchButton: "Buscar",
    searchLoading: "Buscando…",
    searchEmpty: "Nada encontrado.",
    searchEmptyManual: "adicionar manualmente",
    searchErrorNetwork:
      "Sem conexão. A busca precisa de internet, mas seu texto continua seguro no seu navegador.",
    searchErrorRateLimit:
      "Muitas buscas seguidas — espere alguns segundos e tente de novo.",
    searchPartialFailure: "Um catálogo não respondeu — mostrando resultados parciais.",
    searchResultAdd: "Adicionar",
    searchResultAdded: "Já está nas suas referências ✓",
    searchBackToList: "← Voltar à lista",
    privacyNotice:
      "A busca consulta catálogos acadêmicos públicos na internet (CrossRef, Semantic Scholar). Só o que você digita nesta caixa é enviado — seu trabalho continua 100% no seu navegador.",
    addedToastPrefix: "Adicionada! Para citar no texto use",
    addedToastCopy: "copiar",
    addedToastCopied: "copiado!",
    insertCitation: "Inserir citação no texto",
    copyCitation: "copiar citação",
    copiedCitation: "copiado!",
    copiedAnnouncement: "Citação copiada para a área de transferência.",
    copyFailed: "Não foi possível copiar — selecione o texto e copie à mão.",
  },
  sobre: {
    title: "Sobre o UeceTexLive",
    privacy: "Tudo acontece no seu navegador: seu texto nunca sai do seu computador.",
    wikiIntro: "Tutoriais passo a passo, solução de problemas e mais estão na",
    wikiLink: "Wiki do projeto",
    backupTitle: "Backup",
    backupBody:
      "Seu trabalho vive neste navegador, neste computador. Não há servidor, não há conta — o que é ótimo pra privacidade, mas quer dizer que limpar os dados do site (ou trocar de computador) apaga tudo. Exporte cópias regularmente pelo menu “Exportar projeto (.zip)” — o UeceTexLive também lembra você disso de vez em quando.",
  },
  compliance: {
    title: "Meu trabalho está certo?",
    railEntry: "Conformidade",
    pendingHint: "Confira se seu trabalho segue as normas da UECE",
    pendingTabHint: "Pendências: {items}. Verificações com pendência: {checks}.",
    railSummaryOne: "1 item a corrigir",
    railSummaryMany: "{n} itens a corrigir",
    allClearRail: "Tudo certo",
    showOkItems: "ver o que está certo",
    hideOkItems: "ocultar itens corretos",
    close: "Fechar",
    fixAction: "corrigir",
    nextItem: "próximo",
    nextOverall: "Corrigir o próximo",
    expandItems: "ver itens",
    collapseItems: "ocultar itens",
    gotoItem: "ir para",
    notNavigable: "Não há atalho para esta pendência.",
    visitedItem: "já visitado",
    pretextualOk: "Os dados do trabalho (título, autor, orientador…) estão preenchidos.",
    pretextualWarnOne: "Falta preencher 1 dado do trabalho.",
    pretextualWarnMany: "Faltam preencher {n} dados do trabalho.",
    abstractOk: "Resumo e abstract foram escritos.",
    abstractWarn: "Resumo e/ou abstract ainda estão com o texto de exemplo do modelo.",
    referencesOk: "Todas as referências têm os campos obrigatórios preenchidos.",
    referencesWarnOne: "1 referência está com campo obrigatório faltando.",
    referencesWarnMany: "{n} referências estão com campo obrigatório faltando.",
    referenceMissingFields: "Faltam: {fields}.",
    figuresOk: "Todas as figuras têm legenda e indicação de fonte.",
    figuresWarnOne: "1 figura está sem legenda ou sem indicação de fonte.",
    figuresWarnMany: "{n} figuras estão sem legenda ou sem indicação de fonte.",
    figureFallbackLabel: "Figura {n} de {file}",
    figureNoCaption: "Sem legenda.",
    figureNoFonte: "Sem indicação de fonte.",
    figureNoBoth: "Sem legenda e sem indicação de fonte.",
    orphanCitationsOk: "Toda citação no texto tem uma referência correspondente.",
    orphanCitationsWarnOne: "1 citação no texto não tem referência correspondente.",
    orphanCitationsWarnMany: "{n} citações no texto não têm referência correspondente.",
    uncitedEntriesOk: "Toda referência cadastrada foi citada no texto.",
    uncitedEntriesWarnOne: "1 referência cadastrada nunca foi citada no texto.",
    uncitedEntriesWarnMany: "{n} referências cadastradas nunca foram citadas no texto.",
    importPdfOk: "A importação do PDF não deixou nada pendente.",
    importPdfWarnOne: "1 trecho do PDF importado precisa da sua revisão.",
    importPdfWarnMany: "{n} trechos do PDF importado precisam da sua revisão.",
    markerHint:
      "O aviso some quando você usa “já revisei” para retirar o marcador do texto.",
    markerReviewedAction: "já revisei",
    importUnclassifiedHelp:
      "Reescreva este trecho no capítulo certo, consultando o PDF original.",
    importLegacyHelp: "Revise este trecho consultando o PDF original.",
  },
} as const;
